### ISSUE TITLE
Mobile viewport issues

### ISSUE THREAD

**Issue by addison-grant** [RepairAssociation/action-banner#10]
iPhone SE 2020 viewport: banner is quite large. I wonder if we can make it more compact while preserving the information it contains, and keeping the buttons large enough to be usable on mobile. The bottom padding also seems too big.
![image](https://user-images.githubusercontent.com/10889879/104771566-5bc65e00-5727-11eb-98e0-ba428e3fb4aa.png)
![image](https://user-images.githubusercontent.com/10889879/104771574-5d902180-5727-11eb-85f7-9c4730a34603.png)

Aside, desktop at mobile viewport width: this may be less important, since most desktop users probably won't be using a window so narrow, but it would be better if it did not break at narrow widths. Noticed this on ifixit as well as on the demo page https://assets.repair.org/demo.html
![image](https://user-images.githubusercontent.com/10889879/104771630-684ab680-5727-11eb-97a9-372871fa07e1.png)

**Comment by timothyasp** [comment]
Fixed
