### ISSUE TITLE
Iframe height too large

### ISSUE THREAD

**Issue by jarstelfox** [RepairAssociation/action-banner#15]
![Screen Shot 2021-05-04 at 1 20 05 PM](https://user-images.githubusercontent.com/857362/117065304-2f395080-acdc-11eb-80c3-c410c3b26309.jpg)

![Screen Shot 2021-05-04 at 1 26 06 PM](https://user-images.githubusercontent.com/857362/117065389-4ed07900-acdc-11eb-9672-2d1850bd82ff.jpg)

Something with this code https://github.com/RepairAssociation/action-banner/blob/648a7fef393ea9f25f7315f2dc10e80250cb876a/static/widget.js#L134-L139

**Comment by timothyasp** [comment]
Alright, I think I've resolved the issue by just sticking a `ResizeObserver` on the iframe `body` element.  Now it'll post up to the parent iframe and resize on browser size change or orientation change.  

Worth testing to make sure it doesnt' cause any performance issues before deploying.  It didn't in the test page, but that's a fairly simple HTML doc without any other JS.

**Comment by timothyasp** [comment]
Fixed
