### ISSUE TITLE
Cross-domain errors on Google Cloud function request

### ISSUE THREAD

**Issue by sctice** [RepairAssociation/action-banner#6]
We're including this widget on ifixit.com, and it's currently failing to make a request to a Google Cloud function, `geoip-go` because it's cross-domain and there doesn't appear to be a CORS exception. I'm a little puzzled as to why it just recently started failing for this reason. 

Additionally, we've seen one 429 Too Many Requests response, and the widget appears to do a synchronous XMLHttpRequest, which is deprecated.

![image](https://user-images.githubusercontent.com/194351/98602591-51f72900-22a6-11eb-882d-96e9660bd661.png)

**Comment by timothyasp** [comment]
This has been fixed.
